# Generated by Django 4.2.27 on 2026-01-22 02:35

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_options_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
