# Generated by Django 4.2.27 on 2026-01-29 02:19

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='О нас / О компании / История', max_length=100, verbose_name='О нас')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'О нас',
            },
        ),
    ]
