# Generated by Django 4.2.27 on 2026-01-29 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('exp', models.CharField(max_length=100, verbose_name='Опыт')),
            ],
            options={
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название соцсети')),
                ('link', models.CharField(max_length=255, verbose_name='Ссылка на аккаунт')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.team', verbose_name='Сотрудник')),
            ],
        ),
    ]
