# Generated by Django 4.2.27 on 2026-01-30 05:11

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_team_sociallink'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='biog',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Биография'),
        ),
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(null=True, upload_to='teams/', verbose_name='Фото'),
        ),
    ]
