# Generated by Django 4.2.27 on 2026-01-30 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_team_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageShotsTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название фотки')),
                ('img', models.ImageField(upload_to='shotsImage')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.team', verbose_name='Сотрудник')),
            ],
        ),
    ]
